# Generated by Django 2.2.4 on 2020-12-12 18:33

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='KONU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ders_kodu', models.CharField(max_length=20)),
                ('isim', models.CharField(max_length=50)),
                ('ders_alan', models.CharField(choices=[('tyt', 'Temel Yeterlilik Testi'), ('ayt', 'Alan Yeterlilik Testi'), ('both', 'AYT ve TYT')], default=('both', 'AYT ve TYT'), max_length=20)),
                ('KONUNUN_DERSI', models.CharField(choices=[('MAT', 'Matematik'), ('GEO', 'Geometri')], default=('MAT', 'Matematik'), max_length=30)),
                ('ders_text', models.TextField(default='Ders hk. bilgi')),
                ('soru_Sayisi', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Konular',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Solved_problems_count', models.FloatField(default=0, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
