# Generated by Django 2.2.4 on 2020-12-12 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_isim', models.CharField(default='DefaultTest', max_length=50)),
                ('test_konu', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Posts.KONU')),
            ],
            options={
                'verbose_name_plural': 'Testler',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru_adet', models.FloatField(default=0)),
                ('dogru_adet', models.FloatField(default=0)),
                ('yanlis_adet', models.FloatField(default=0)),
                ('ogrenci', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Posts.User')),
                ('test', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Questions.Testler')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(default=1)),
                ('question', models.TextField(default='', max_length=300)),
                ('option1', models.CharField(default='', max_length=100)),
                ('option2', models.CharField(default='', max_length=100)),
                ('option3', models.CharField(default='', max_length=100)),
                ('option4', models.CharField(default='', max_length=100)),
                ('option5', models.CharField(default='', max_length=100)),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='a', max_length=10)),
                ('question_test', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Questions.Testler')),
            ],
            options={
                'verbose_name_plural': 'Sorular',
            },
        ),
    ]
